// Package builtin contains immutable declarations for the Skills shipped with
// the application. Installation and publication remain explicit operations;
// a declaration never gives a model arbitrary protocol access.
package builtin

import (
	"encoding/json"
	"time"

	"opskeeper/backend/connector"
	"opskeeper/backend/skill"
)

type Definition struct {
	Key        string
	Manifest   skill.Manifest
	Tools      []skill.ToolSpec
	Capability connector.Capability
	Timeout    time.Duration
}

func Definitions() []Definition {
	inspectSchema := json.RawMessage(`{"type":"object","required":["target_resource_id"],"properties":{"target_resource_id":{"type":"string"}},"additionalProperties":false}`)
	return []Definition{
		{Key: "kubernetes-workload", Manifest: skill.Manifest{Name: "Kubernetes 工作负载诊断", Description: "只读检查工作负载、Pod、事件、探针与发布状态。", Instruction: "仅调用声明的只读 Kubernetes 工具。将事实、异常和待验证假设明确分离。"}, Tools: []skill.ToolSpec{{Name: "connector_kubernetes_read", Description: "受限读取 Kubernetes 对象。", InputSchema: json.RawMessage(`{"type":"object","required":["target_resource_id","resource"],"properties":{"target_resource_id":{"type":"string"},"resource":{"type":"string"},"namespace":{"type":"string"},"name":{"type":"string"},"label_selector":{"type":"string"},"limit":{"type":"integer"}},"additionalProperties":false}`)}}, Capability: connector.CapabilityKubernetesRead, Timeout: 10 * time.Second},
		{Key: "postgresql-health", Manifest: skill.Manifest{Name: "PostgreSQL 健康诊断", Description: "只读检查 PostgreSQL 健康、性能、表、VACUUM、扩展和数据库信息。", Instruction: "调用 PostgreSQL 固定只读工具；不要请求或建议写 SQL。"}, Tools: []skill.ToolSpec{{Name: "postgresql_health", Description: "检查 PostgreSQL 健康。", InputSchema: inspectSchema}, {Name: "postgresql_tables", Description: "读取用户表统计。", InputSchema: inspectSchema}, {Name: "postgresql_table_columns", Description: "读取指定用户表列信息。", InputSchema: inspectSchema}, {Name: "postgresql_performance", Description: "读取性能与配置。", InputSchema: inspectSchema}, {Name: "postgresql_vacuum", Description: "读取 VACUUM 配置。", InputSchema: inspectSchema}, {Name: "postgresql_extensions", Description: "读取扩展信息。", InputSchema: inspectSchema}, {Name: "postgresql_database_info", Description: "读取数据库概要。", InputSchema: inspectSchema}}, Capability: connector.CapabilityPostgreSQLHealth, Timeout: 10 * time.Second},
		{Key: "mysql-health", Manifest: skill.Manifest{Name: "MySQL 健康诊断", Description: "只读检查 MySQL 状态、性能、配置、表和数据库信息。", Instruction: "调用 MySQL 固定只读工具；不要请求或建议写 SQL。"}, Tools: []skill.ToolSpec{{Name: "mysql_health", Description: "检查 MySQL 健康。", InputSchema: inspectSchema}, {Name: "mysql_status", Description: "读取 MySQL 状态。", InputSchema: inspectSchema}, {Name: "mysql_performance", Description: "读取性能与配置。", InputSchema: inspectSchema}, {Name: "mysql_tables", Description: "读取用户表信息。", InputSchema: inspectSchema}, {Name: "mysql_table_columns", Description: "读取指定表列信息。", InputSchema: inspectSchema}, {Name: "mysql_table_structure", Description: "读取指定表结构和索引。", InputSchema: inspectSchema}, {Name: "mysql_database_info", Description: "读取数据库概要。", InputSchema: inspectSchema}}, Capability: connector.CapabilityMySQLHealth, Timeout: 10 * time.Second},
		{Key: "oracle-health", Manifest: skill.Manifest{Name: "Oracle 健康诊断", Description: "只读检查 Oracle 状态、性能、配置、表和数据库信息。", Instruction: "调用 Oracle 固定只读工具；不要请求或建议写 SQL。"}, Tools: []skill.ToolSpec{{Name: "oracle_health", Description: "检查 Oracle 健康。", InputSchema: inspectSchema}, {Name: "oracle_status", Description: "读取 Oracle 状态。", InputSchema: inspectSchema}, {Name: "oracle_performance", Description: "读取性能与配置。", InputSchema: inspectSchema}, {Name: "oracle_database_info", Description: "读取数据库概要。", InputSchema: inspectSchema}, {Name: "oracle_tables", Description: "读取用户表信息。", InputSchema: inspectSchema}, {Name: "oracle_table_columns", Description: "读取指定表列信息。", InputSchema: inspectSchema}, {Name: "oracle_table_structure", Description: "读取指定表结构。", InputSchema: inspectSchema}}, Capability: connector.CapabilityOracleHealth, Timeout: 10 * time.Second},
		{Key: "redis-health", Manifest: skill.Manifest{Name: "Redis 健康诊断", Description: "只读检查 Redis 健康、内存、客户端、复制、慢命令和数据库信息。", Instruction: "调用 Redis 固定只读工具；不要请求或建议写命令。"}, Tools: []skill.ToolSpec{{Name: "redis_health", Description: "检查 Redis 健康。", InputSchema: inspectSchema}, {Name: "redis_memory", Description: "读取内存统计。", InputSchema: inspectSchema}, {Name: "redis_clients", Description: "读取客户端统计。", InputSchema: inspectSchema}, {Name: "redis_replication", Description: "读取复制状态。", InputSchema: inspectSchema}, {Name: "redis_slowlog", Description: "读取慢日志。", InputSchema: inspectSchema}, {Name: "redis_database_info", Description: "读取数据库信息。", InputSchema: inspectSchema}}, Capability: connector.CapabilityRedisInspect, Timeout: 10 * time.Second},
		{Key: "kafka-health", Manifest: skill.Manifest{Name: "Kafka 健康诊断", Description: "只读检查 Broker、Topic、分区、ISR、消费组和积压。", Instruction: "调用 Kafka 固定只读工具；不要请求或建议管理操作。"}, Tools: []skill.ToolSpec{{Name: "kafka_health", Description: "读取 Kafka 健康摘要。", InputSchema: inspectSchema}, {Name: "kafka_brokers", Description: "读取 Broker。", InputSchema: inspectSchema}, {Name: "kafka_topics", Description: "读取 Topic 指标。", InputSchema: inspectSchema}, {Name: "kafka_consumer_groups", Description: "读取消费组。", InputSchema: inspectSchema}, {Name: "kafka_consumer_lag", Description: "读取消费积压。", InputSchema: inspectSchema}, {Name: "kafka_cluster_info", Description: "读取集群元信息。", InputSchema: inspectSchema}, {Name: "kafka_topic_partitions", Description: "读取指定 Topic 分区。", InputSchema: inspectSchema}}, Capability: connector.CapabilityKafkaInspect, Timeout: 10 * time.Second},
		{Key: "elasticsearch-health", Manifest: skill.Manifest{Name: "Elasticsearch 健康诊断", Description: "只读检查 Elasticsearch 集群、节点、索引和分片。", Instruction: "调用 Elasticsearch 固定只读工具；不要请求管理操作。"}, Tools: []skill.ToolSpec{{Name: "elasticsearch_health", Description: "读取集群健康。", InputSchema: inspectSchema}, {Name: "elasticsearch_cluster_info", Description: "读取集群信息。", InputSchema: inspectSchema}, {Name: "elasticsearch_nodes", Description: "读取节点信息。", InputSchema: inspectSchema}, {Name: "elasticsearch_indices", Description: "读取索引指标。", InputSchema: inspectSchema}, {Name: "elasticsearch_shards", Description: "读取分片摘要。", InputSchema: inspectSchema}, {Name: "elasticsearch_settings", Description: "读取集群配置。", InputSchema: inspectSchema}, {Name: "elasticsearch_index_mapping", Description: "读取索引映射。", InputSchema: inspectSchema}}, Capability: connector.CapabilityElasticsearchInspect, Timeout: 10 * time.Second},
		{Key: "rabbitmq-health", Manifest: skill.Manifest{Name: "RabbitMQ 健康诊断", Description: "只读检查 RabbitMQ 集群、节点、队列、交换机、连接和消费者。", Instruction: "调用 RabbitMQ Management API 固定只读工具；不要执行写操作。"}, Tools: []skill.ToolSpec{{Name: "rabbitmq_health", Description: "读取 RabbitMQ 健康摘要。", InputSchema: inspectSchema}, {Name: "rabbitmq_overview", Description: "读取集群概要。", InputSchema: inspectSchema}, {Name: "rabbitmq_nodes", Description: "读取节点。", InputSchema: inspectSchema}, {Name: "rabbitmq_queues", Description: "读取队列。", InputSchema: inspectSchema}, {Name: "rabbitmq_exchanges", Description: "读取交换机。", InputSchema: inspectSchema}, {Name: "rabbitmq_connections", Description: "读取连接。", InputSchema: inspectSchema}, {Name: "rabbitmq_channels", Description: "读取通道。", InputSchema: inspectSchema}, {Name: "rabbitmq_consumers", Description: "读取消费者。", InputSchema: inspectSchema}, {Name: "rabbitmq_vhosts", Description: "读取虚拟主机。", InputSchema: inspectSchema}}, Capability: connector.CapabilityRabbitMQInspect, Timeout: 10 * time.Second},
		{Key: "minio-health", Manifest: skill.Manifest{Name: "MinIO 健康诊断", Description: "只读检查 MinIO 连接、存储桶、对象和桶配置。", Instruction: "调用 MinIO 固定只读工具；不要执行写入、删除或管理操作。"}, Tools: []skill.ToolSpec{{Name: "minio_health", Description: "读取 MinIO 健康摘要。", InputSchema: inspectSchema}, {Name: "minio_buckets", Description: "读取存储桶。", InputSchema: inspectSchema}, {Name: "minio_bucket_objects", Description: "读取指定存储桶对象。", InputSchema: inspectSchema}, {Name: "minio_object_stat", Description: "读取对象元数据。", InputSchema: inspectSchema}, {Name: "minio_bucket_versioning", Description: "读取存储桶版本配置。", InputSchema: inspectSchema}, {Name: "minio_bucket_lifecycle", Description: "读取存储桶生命周期配置。", InputSchema: inspectSchema}}, Capability: connector.CapabilityMinIOInspect, Timeout: 10 * time.Second},
	}
}
