<script lang="ts">
  import { kubernetesAccessModeLabel, type KubernetesAccessMode } from './resourceWorkflow';
  export let accessMode: KubernetesAccessMode = 'direct'; export let server=''; export let token=''; export let kubeconfig=''; export let context=''; export let skipTLSVerify=false; export let connectionOverride=false; export let mcpServerResourceId=''; export let mcpServers: any[]=[]; export let credentialLoading=false; export let onConfigurationChange:()=>void=()=>{};
</script>
<div class="docker-connection-form">
  <div class="docker-agent-connection-row"><label><span>接入方式</span><select bind:value={accessMode} on:change={onConfigurationChange}><option value="direct">{kubernetesAccessModeLabel('direct')}</option><option value="agent">{kubernetesAccessModeLabel('agent')}</option></select></label>{#if accessMode === 'agent'}<label><span>关联 MCPServer</span><select bind:value={mcpServerResourceId} on:change={onConfigurationChange}><option value="">请选择</option>{#each mcpServers as server}<option value={server.id}>{server.name}</option>{/each}</select></label><label><span>自定义连接</span><input type="checkbox" bind:checked={connectionOverride} on:change={onConfigurationChange}/></label>{/if}</div>
  {#if accessMode === 'direct' || connectionOverride}<div class="docker-form-grid"><label><span>API Server 地址</span><input bind:value={server} on:input={onConfigurationChange} placeholder="https://kubernetes.example:6443" /></label><label><span>Context</span><input bind:value={context} on:input={onConfigurationChange} /></label><label><span>Token（可选）</span><input type="password" bind:value={token} on:input={onConfigurationChange} /></label><label><span>跳过 TLS 校验</span><input type="checkbox" bind:checked={skipTLSVerify} on:change={onConfigurationChange}/></label><label class="docker-host-field"><span>Kubeconfig（可选）</span><textarea rows="7" bind:value={kubeconfig} on:input={onConfigurationChange} placeholder="粘贴 kubeconfig；优先于 API Server"></textarea></label></div>{/if}
  {#if credentialLoading}<small>正在读取已有凭据...</small>{/if}
</div>
