apiVersion: v1
kind: ServiceAccount
metadata:
  name: opskeeper-sandbox
  namespace: opskeeper
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opskeeper-operation-runner
  namespace: opskeeper
automountServiceAccountToken: true
